resolver: nightly-2017-09-20

packages:
  - '.'
  - location:
      git: git@github.com:adjoint-io/merkle-tree
      commit: a942ee26f56d24473757af5d1bda48c39b2ebd44
    extra-dep: true

extra-deps:
  - pipes-network-0.6.4.1
  - base58-bytestring-0.1.0
  - containers-0.5.10.2

flags: {}

extra-package-dbs: []
